//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficiary()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string Beneficiary_Name { get; set; }
        public long Beneficiary_Account_Number { get; set; }
        public string Save_Status { get; set; }
        public string Nick_Name { get; set; }
        public Nullable<int> User_Account { get; set; }
    
        public UsersAccount UsersAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<Transaction> Transactions { get; set; }
    }
}
